### ISSUE TITLE
how to detect the watermark?

### ISSUE THREAD

**Issue by LeoStrange26** [THU-BPM/Robust_Watermark#3]
Having read your paper, I still cannot understand why the formula mentioned in the article can detect watermark. Hope the author can answer. Thx

<img width="207" alt="79d1cedd075c976a25bdec4986d2448" src="https://github.com/THU-BPM/Robust_Watermark/assets/98246362/c5f82edf-1ae8-4fcb-8d73-c7fd9f0c024c">

**Comment by exlaw** [comment]
You could refer to our revised version in the ICLR submission https://openreview.net/pdf?id=6p8lpe4MNf,  we added some explanation there. If there are still any questions,  please let me know.

**Comment by KahimWong** [comment]
Hi, I am still confused about the method. After paraphrasing the watermarked text, a token in j step would probably change, by computing whether this toke falls into green/red list is misleading since this token is not the token in the watermarked text.

**Comment by exlaw** [comment]
Thank you for your attention to our work. There was a slight oversight in the detection formula in the initial arXiv version, which should actually be \(P_W^{t_j}\). Therefore, the detection of the watermark is actually independent of its position j. Please refer to our latest version on arXiv https://arxiv.org/pdf/2310.06356.pdf  and the camera-ready version for ICLR 2024 https://openreview.net/pdf?id=6p8lpe4MNf .  
If you have any further questions, please feel free to communicate at any time.
