### ISSUE TITLE
Question about _get_bias method in WatermarkContext class

### ISSUE THREAD

**Issue by ObsisMc** [THU-BPM/Robust_Watermark#4]
Why does it return a `-similarity_array` rather than `similarity_array`?
https://github.com/THU-BPM/Robust_Watermark/blob/a076d2672a8cc332d6f45f51aa901066af176582/watermark.py#L145-L150

**Comment by exlaw** [comment]
Thank you for your attention. Here, the reason for '-similarity_array' is because at line 142, we also used '-float(similarity_array[tokens[0][index]])'. Removing the '-' in both places would also work perfectly.

**Comment by ObsisMc** [comment]
Thanks a lot.
