### ISSUE TITLE
复现论文的问题

### ISSUE THREAD

**Issue by DrankXs** [THU-BPM/Robust_Watermark#6]
我下载了代码并尝试复现论文中的实验结果，但是在使用context模式的时候，始终无法得到很好的效果。我确保了训练TransformModel时的超参数和论文中的一致，数据使用和github中的一致。我执行的脚本如下所示:
`python watermark_and_detect.py  --watermark_type context   --base_model opt27b    --llm_path xxxx/opt-2.7b    --generate_number 500    --delta 1    --chunk_size 10    --max_new_tokens 200    --data_path data/dataset/c4-en-5000.jsonl    --output_path result/opt27b_context_result_500.jsonl    --transform_model model/paper_param_model.pth    --embedding_model xxx/compositional-bert-large-uncased     --decode_method sample
`
但分析结果后并没有得到一个可以接受的结果。

**Comment by exlaw** [comment]
你好，感谢关注我们的工作。 关于复现，是否可以提供更多细节，比如你们的结果具体是多少。 或者如果需要更详细的交流和支持可以加我的wechat：u839134412。
